#include "config.h"

import "shobjidl.idl";

[
	uuid(110e1da1-3e28-4133-a05c-ca13d5e4a34a),
	version(1.0),
]
library LxRunOfflineShellExtLib {
	[uuid(HANDLER_CLSID_STR)]
	coclass ContextMenuHandler {
		[default] interface IShellExtInit;
		interface IContextMenu;
	};
};
