on: push
jobs:
  build-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - env:
          MSYSTEM: MINGW64
        run: |
          $ErrorActionPreference = "Continue"
          C:\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm --noprogressbar"
          C:\msys64\usr\bin\bash.exe -l -c "pacman -Syu --needed --noconfirm --noprogressbar base-devel cmake git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libarchive mingw-w64-x86_64-boost mingw-w64-x86_64-tinyxml2"
          git fetch --unshallow --tags
          C:\msys64\usr\bin\bash.exe -l -c "
            cd /d/a/LxRunOffline/LxRunOffline &&
            cmake -G 'MSYS Makefiles' -DCMAKE_BUILD_TYPE=Release . &&
            make package -j"
          if ($LASTEXITCODE -ne 0) { Exit 1 }
      - if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: |
          $zip_name = "LxRunOffline-$(git describe --tags)-mingw.zip"
          curl.exe -fsS `
            -T $zip_name `
            -u ddosolitary:${{ secrets.BINTRAY_KEY }} `
            -H "X-Bintray-Package: default" `
            -H "X-Bintray-Version: default" `
            -H "X-Bintray-Publish: 1" `
            https://api.bintray.com/content/ddosolitary/dev-releases/LxRunOffline/$zip_name
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - env:
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
        run: |
          $ErrorActionPreference = "Continue"
          pushd $Env:VCPKG_INSTALLATION_ROOT
          git pull
          .\bootstrap-vcpkg.bat
          popd
          vcpkg integrate install
          vcpkg install libarchive boost-program-options boost-format tinyxml2
          git fetch --unshallow --tags
          cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" & set' |
            foreach { if ($_ -match "=") { $v = $_.split("="); Set-Item -Force -Path "Env:\$($v[0])" -Value "$($v[1])" } }
          cmake . `
            -G "NMake Makefiles" `
            -DCMAKE_TOOLCHAIN_FILE="$Env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="$Env:VCPKG_DEFAULT_TRIPLET" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_CHOCO_PKG=ON
          nmake package
          if ($LASTEXITCODE -ne 0) { Exit 1 }
      - if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: |
          $version = git describe --tags
          $zip_name = "LxRunOffline-$version-msvc.zip"
          curl.exe -fsS `
            -T $zip_name `
            -u ddosolitary:${{ secrets.BINTRAY_KEY }} `
            -H "X-Bintray-Package: default" `
            -H "X-Bintray-Version: default" `
            -H "X-Bintray-Publish: 1" `
            https://api.bintray.com/content/ddosolitary/dev-releases/LxRunOffline/$zip_name
          if (-not $version.Contains("-")) {
            cmake -DCOMPONENT=choco -DCMAKE_INSTALL_PREFIX="$PWD" -P cmake_install.cmake
            $pkg_name = "lxrunoffline.$($version.Substring(1)).nupkg"
            curl.exe -fsS `
              -T $pkg_name `
              -u ddosolitary:${{ secrets.BINTRAY_KEY }} `
              -H "X-Bintray-Package: default" `
              -H "X-Bintray-Version: default" `
              -H "X-Bintray-Publish: 1" `
              https://api.bintray.com/content/ddosolitary/dev-releases/LxRunOffline/$pkg_name
          }
